In [16]:
# contoh 2.20.1
# operasi suatu matrik
import numpy as np
matrik_1_22 = np.array([1,2,3,4])
matrik_2_22 = np.array([5,7,9,11])
    #penjumlahan_22
result_1_22 = (matrik_1_22 + matrik_2_22)
print(result_1_22)

[ 6  9 12 15]


In [17]:
# contoh 2.20.1
# operasi suatu matrik
import numpy as np
matrik_1_22 = np.array([2,4,6,8])
matrik_2_22 = np.array([10,20,30,40])
    #perkalian_22
result_2_22 = (matrik_1_22 * matrik_2_22)
print(result_2_22)

[ 20  80 180 320]


In [18]:
result_1_22.ndim

1

In [20]:
result_2_22.ndim

1

In [22]:
result_1_22.shape

(4,)

In [24]:
result_2_22.shape

(4,)

In [81]:
# contoh 2.20.2
# matrik 3x3
# memanggil anggota pada baris 1
a_22 = np.array([10,11,12,13])
b_22 = np.array([14,15,16,17])
c_22 = np.array([18,19,20,21])
print (a_22,b_22,c_22)

[10 11 12 13] [14 15 16 17] [18 19 20 21]


In [82]:
# contoh 2.20.2
# matrik 4x4
a_22 = np.array([[10,15,20,25],[30,35,40,45],[50,55,60,65],[70,75,80,85]])
print(a_22)

[[10 15 20 25]
 [30 35 40 45]
 [50 55 60 65]
 [70 75 80 85]]


In [83]:
a_22[0,2]

20